# basic workflow for a golang project
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  # the build workflow
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'
      
      # install the dependencies
      - name: Install dependencies
        run: |
          go version
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run vet and lint
        run: |
          go vet .
          golangci-lint run ./...
